name: Run script on merge
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Bash
        uses: actions/setup-bash@v1

      - name: Run Script
        run: ./test.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
